HutechDriver/Areas/Admin/Controllers/PriceController.cs
using HutechDriver.Models;
using HutechDriver.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HutechDriver.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PriceController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Price

        public ActionResult Index(string SearchText, int? page)
        {
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<PriceTrip> items = db.Pricetrips.OrderByDescending(x => x.Id);

            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Edit(int id)
        {
            var item = db.Pricetrips.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PriceTrip model)
        {
            if (ModelState.IsValid)
            {
                var price = db.Pricetrips.Find(model.Id);
                price.Price = model.Price;
                price.PriceLow = model.PriceLow;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

HutechDriver/Areas/Admin/Views/Price/Edit.cshtml
@model HutechDriver.Models.EF.PriceTrip
@{
    ViewBag.Title = "Cập nhật tin tức";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/manager/home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/manager/news" class="nav-link">Tin tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/manager/category" class="nav-link">Cập nhật</a>
        </li>
    </ul>}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới Tin tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Cập nhật</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin cập nhật Tin tức</h3>
        </div>
        <div class="card-body">

            <div class="col-lg-3 col-6">
                <div class="small-box bg-info">
                    <div class="inner">
                        @if (Model != null)
                        {
                            <div class="bs-stepper-content">
                                @using (Html.BeginForm("Edit", "Price", FormMethod.Post, new { }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)


                                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">

                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Price / 1km</label>
                                        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Price < 1km</label>
                                        @Html.TextBoxFor(x => x.PriceLow, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <a style="background-color: red;" href="/admin/price" class="btn btn-primary">Quay lại</a>
                                        <button style="background-color: green;" type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                                }
                                <!-- your steps content here -->

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}

HutechDriver/Areas/Admin/Views/Price/Index.cshtml
@model PagedList.PagedList<HutechDriver.Models.EF.PriceTrip>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Price";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/manager/home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/manager/category" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Price Trip </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách @ViewBag.Title</h3>


        </div>






        <div class="card-body">

            <div class="col-lg-3 col-6">
                <div class="small-box bg-info">
                    <div class="inner">
                        @if (Model != null && Model.Any())
                        {
                            var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                            foreach (var item in Model)
                            {
                                <h3 id=" trow_@item.Id">
                                    Giá: @HutechDriver.Common.Common.FormatNumber(@item.Price) Vnđ
                                </h3>
                                <div class="icon">
                                    <i class="fas fa-dollar-sign"></i>
                                </div> <br />
                                <a href="/admin/price/edit/@item.Id" class="small-box-footer">
                                    Thay đổi <i class="fas fa-arrow-circle-right"></i>
                                </a>
                            }
                        }



                    </div>




                </div>

            </div>
            <div class="col-lg-3 col-6">
                <div class="small-box bg-info">
                    <div class="inner">
                        @if (Model != null && Model.Any())
                        {
                            var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                            foreach (var item in Model)
                            {
                                <h3 id=" trow_@item.Id">
                                    Giá: @HutechDriver.Common.Common.FormatNumber(@item.PriceLow) Vnđ
                                </h3>
                                <div class="icon">
                                    <i class="fas fa-dollar-sign"></i>
                                </div> <br />
                                <a href="/admin/price/edit/@item.Id" class="small-box-footer">
                                    Thay đổi <i class="fas fa-arrow-circle-right"></i>
                                </a>
                            }
                        }



                    </div>




                </div>

            </div>
        </div>
        </div>
    <!-- /.card -->

</section>
<!-- /.content -->